urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name='barkasse'
urlpatterns = [
    path('', views.HouseholdList.as_view(), name='households'),
    path('<int:hh>/', views.HomeView.as_view(), name='home'),
    path('<int:hh>/tr/', views.TransactionList.as_view(), name='transactions'),
    path('<int:hh>/tr/create/', views.TransactionCreate.as_view(), name='transaction_create'),
    path('<int:hh>/tr/<int:pk>/update/', views.TransactionUpdate.as_view(), name='transaction_update'),
    path('<int:hh>/tr/<int:pk>/delete/', views.TransactionDelete.as_view(), name='transaction_delete'),
    path('<int:hh>/shop/', views.ShopList.as_view(), name='shops'),
    path('<int:hh>/shop/create/', views.ShopCreate.as_view(), name='shop_create'),
    path('<int:hh>/shop/<int:pk>/update/', views.ShopUpdate.as_view(), name='shop_update'),
    path('<int:hh>/shop/<int:pk>/delete/', views.ShopDelete.as_view(), name='shop_delete'),
    path('<int:hh>/account/', views.AccountList.as_view(), name='accounts'),
    path('<int:hh>/account/create/', views.AccountCreate.as_view(), name='account_create'),
    path('<int:hh>/account/<int:pk>/update/', views.AccountUpdate.as_view(), name='account_update'),
    path('<int:hh>/account/<int:pk>/delete/', views.AccountDelete.as_view(), name='account_delete'),
    path('<int:hh>/export/', views.ExportView.as_view(), name='export'),
    path('<int:hh>/export/<int:year>/<int:month>', views.export_csv_view, name='export_csv'),
]

templates/barkasse/account_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Konto löschen</h1>

<p>Willst du das Konto '{{ account }}' und alle Transaktionen davon wirklich löschen?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-primary" type="submit" value="Ja, löschen.">
  <input class="btn btn-secondary" type="submit" onclick="window.location='{% url 'barkasse:accounts' hh %}' ; return false;" value="Abbrechen">
</form>

{% endblock %}

templates/barkasse/account_form.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<h1>Konto hinzufügen/bearbeiten</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input class="btn btn-primary" type="submit" value="Speichern">
    <input class="btn btn-secondary" type="submit" onclick="window.location='{% url 'barkasse:accounts' hh %}' ; return false;" value="Abbrechen">
  </form>
{% endblock %}

templates/barkasse/account_list.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ hh_name }} / Kontenliste</h1>
  {% if account_list %}
  <table class="table table-striped">
  <tbody>
    {% for account in account_list %}
      <tr>
        <td>
          <strong>{{ account.name }}</strong> ({{ account.comment }})
        </td>
        <td>
          <a href="{% url 'barkasse:account_update' hh account.id %}">Update</a> |
          <a href="{% url 'barkasse:account_delete' hh account.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>Keine Konten vorhanden.</p>
  {% endif %}
  <p>
    <a href="{% url 'barkasse:account_create' hh %}">Konto hinzufügen</a> | <a href="{% url 'barkasse:home' hh %}">Startseite</a>
  </p>
{% endblock %}

templates/barkasse/export.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ hh_name }} / Transaktionen exportieren</h1>

 {% if links %}
  <table class="table table-striped">
  <tbody>
   {% for link in links %}
      <tr>
        <td>
          <a href="{{ link.url }}">{{ link.count }} Transaktionen vom {{ link.month }} {{ link.year }}</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  {% else %}
    <p>Keine Transaktionen zum Exportieren vorhanden.</p>
  {% endif %}
  <p>
    <a href="{% url 'barkasse:home' hh %}">Startseite</a>
  </p>
{% endblock %}

templates/barkasse/home.html
{% extends "base.html" %}

{% block content %}
<h1>Barkasse von {{ hh_name }} </h1>



<h2>Aktuelle Transaktionen</h2>
  {% if transaction_list %}
  <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
      <th>Datum</th>
      <th>Ort</th>
      <th>Betrag</th>
      </tr>
    </thead>
  <tbody>
    {% for transaction in transaction_list %}
      <tr>
        <td>
          {{ transaction.date|date:'d.m.Y' }}
        </td>
        <td>
          <strong>{{ transaction.shop }}</strong>
        </td>
        <td class="text-right">
          {{ transaction.amount|floatformat:2 }}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>Keine Transaktionen vorhanden.</p>
  {% endif %}

<a href="{% url 'barkasse:transaction_create' hh %}" class="btn btn-primary btn-block" role="button">Transaktion hinzufügen</a>

<ul class="nav justify-content-center">
  <li class="nav-item"><a href="{% url 'barkasse:transactions' hh %}" class="nav-link">Transaktionen</a></li>
  <li class="nav-item"><a href="{% url 'barkasse:shops' hh %}" class="nav-link">Shops</a></li>
  <li class="nav-item"><a href="{% url 'barkasse:accounts' hh %}" class="nav-link">Konten</a></li>
  <li class="nav-item"><a href="{% url 'barkasse:export' hh %}" class="nav-link">Export</a></li>
  <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Ausloggen</a></li>
</ul>

{% endblock %}

templates/barkasse/household_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Bitte wähle einen Haushalt</h1>
  {% if household_list %}
    {% for household in household_list %}
      <a href="{% url 'barkasse:home' household.id %}" class="btn btn-primary btn-block" role="button">{{household.name}}</a>
    {% endfor %}
  {% else %}
    <p>Kein Haushalt vorhanden. Wende dich an den Administrator.</p>
  {% endif %}
{% endblock %}

templates/barkasse/shop_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Shop löschen</h1>

<p>Willst du den Shop '{{ shop }}' wirklich löschen?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-primary" type="submit" value="Ja, löschen.">
  <input class="btn btn-secondary" type="submit" onclick="window.location='{% url 'barkasse:shops' hh %}' ; return false;" value="Abbrechen">

</form>

{% endblock %}

templates/barkasse/shop_form.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<h1>Shop hinzufügen/bearbeiten</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Speichern">
    <input class="btn btn-secondary" type="submit" onclick="window.location='{% url 'barkasse:shops' hh %}' ; return false;" value="Abbrechen">
  </form>
{% endblock %}

templates/barkasse/shop_list.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ hh_name }} / Shopliste</h1>
  {% if shop_list %}
  <table class="table table-striped">
  <tbody>
    {% for shop in shop_list %}
      <tr>
        <td>
          {{ shop.name }}
        </td>
        <td>
          <a href="{% url 'barkasse:shop_update' hh shop.id %}">Update</a> |
          <a href="{% url 'barkasse:shop_delete' hh shop.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>Keine Shops vorhanden.</p>
  {% endif %}
  <p>
    <a href="{% url 'barkasse:shop_create' hh %}">Shop hinzufügen</a> | <a href="{% url 'barkasse:home' hh%}">Startseite</a>
  </p>
{% endblock %}

templates/barkasse/transaction_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Transaktion löschen</h1>

<p>Willst du die Transaktion mit {{ transaction.amount }} Franken vom {{ transaction.date }} in '{{ transaction.shop }}' wirklich löschen?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="btn btn-primary"type="submit" value="Ja, löschen.">
  <input class="btn btn-secondary" type="submit" onclick="window.location='{% url 'barkasse:transactions' hh %}' ; return false;" value="Abbrechen">

</form>

{% endblock %}

templates/barkasse/transaction_form.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<h1>Transaktion hinzufügen/bearbeiten</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <button type="submit" class="btn btn-primary" value="Speichern">Speichern</button>
  <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'barkasse:transactions' hh %}' ; return false;" value="Abbrechen">Abbrechen</button>
  </form>
{% endblock %}

templates/barkasse/transaction_list.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ hh_name }} / Transaktionen</h1>

 {% if transaction_list %}
  <table class="table table-striped">
  <tbody>
   <thead class="thead-dark">
    <tr>
      <th>Datum</th>
      <th>Ort</th>
      <th>Bezeichnung</th>
      <th>Konto</th>
      <th>Betrag</th>
      <th></th>
      </tr>
    </thead>
    {% for transaction in transaction_list %}
      <tr>
        <td>
          {{ transaction.date|date:'d.m.Y' }}
        </td>
        <td>
          <strong>{{ transaction.shop }}</strong>
        </td>
        <td>
          {{ transaction.title }}
        </td>
        <td>
          {{ transaction.account }}
        </td>
        <td class="text-right">
          {{ transaction.amount|floatformat:2 }}
        </td>
        <td>
          <a href="{% url 'barkasse:transaction_update' hh transaction.id %}">Update</a> |
          <a href="{% url 'barkasse:transaction_delete' hh transaction.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center"">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">&laquo;</a></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="#" tabindex="-1">{{ i }} <span class="sr-only">(current)</span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">&raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

  {% else %}
    <p>Keine Transaktionen vorhanden.</p>
  {% endif %}
  <p>
    <a href="{% url 'barkasse:transaction_create' hh %}">Transaktion hinzufügen</a> | <a href="{% url 'barkasse:home' hh %}">Startseite</a>
  </p>
{% endblock %}